import { useState } from 'react';
import { ArrowLeft, Check, Clock3, Mail, MapPin, Phone, Send } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api from '../../config/axios';
import './public.css';

const contacts = [[Phone, 'Telefon', '+998 90 123 45 67'], [Mail, 'Email', 'info@abdora.ai'], [MapPin, 'Manzil', 'Toshkent, O‘zbekiston'], [Clock3, 'Ish vaqti', '24/7 — Har doim siz bilan']];

export default function ContactPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ name: '', email: '', phone: '', message: '' });
  const [status, setStatus] = useState('idle');
  const submit = async (event) => { event.preventDefault(); setStatus('sending'); try { await api.post('/applications', form); navigate('/contact/success'); } catch { setStatus('error'); } };
  return <main className="public-container"><div className="public-page-heading"><span className="public-eyebrow">Aloqa</span><h1 className="public-title">Biz bilan bog‘laning</h1><p className="public-lede">Savollaringiz bormi yoki qo‘llab-quvvatlashga muhtojmisiz? Biz bilan bog‘laning.</p></div><div className="contact-grid"><div className="contact-info">{contacts.map(([Icon, title, value]) => <div className="public-card contact-card" key={title}><span className="service-icon"><Icon size={18} /></span><div><small>{title}</small><strong>{value}</strong></div></div>)}</div><form className="public-card contact-form public-form" onSubmit={submit}><div className="form-row"><label>Ism Familya<input className="public-field" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Ismingiz" /></label><label>Email<input className="public-field" type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="email@example.com" /></label></div><label>Telefon raqam<input className="public-field" type="tel" required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+998 90 123 45 67" /></label><label>Xabar<textarea className="public-field" rows="5" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Xabaringizni yozing..." /></label><button className="public-button primary" disabled={status === 'sending'} type="submit"><Send size={15} />{status === 'sending' ? 'Yuborilmoqda...' : 'Xabar yuborish'}</button>{status === 'error' && <p className="form-error">Xatolik yuz berdi. Birozdan so‘ng qayta urinib ko‘ring.</p>}</form></div><style>{`.contact-grid{display:grid;grid-template-columns:.75fr 1.25fr;gap:18px;align-items:start}.contact-info{display:grid;gap:10px}.contact-card{padding:18px;display:flex;align-items:center;gap:14px}.contact-card .service-icon{flex:none;width:38px;height:38px;margin:0}.contact-card small,.contact-card strong{display:block}.contact-card small{color:var(--muted);font-size:11px;margin-bottom:5px}.contact-card strong{font-size:13px}.contact-form{padding:26px}.contact-form label{display:grid;gap:7px;color:var(--secondary);font-size:12px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.contact-form .public-button{justify-content:center;border:0;cursor:pointer}.form-error{color:#dc5545;font-size:12px;text-align:center}@media(max-width:760px){.contact-grid{grid-template-columns:1fr}.form-row{grid-template-columns:1fr}}`}</style></main>;
}

export function ContactSuccessPage() {
  return <main className="public-container success-page"><div className="success-mark"><Check size={38} /></div><span className="public-eyebrow">Muvaffaqiyatli</span><h1 className="public-title">Xabaringiz qabul qilindi!</h1><p className="public-lede">Tez orada siz bilan bog‘lanamiz. Bizga ishonchingiz uchun rahmat!</p><a className="public-button primary" href="/"><ArrowLeft size={15} /> Bosh sahifaga qaytish</a><style>{`.success-page{text-align:center;display:flex;align-items:center;flex-direction:column;justify-content:center;min-height:650px}.success-page .public-title{font-size:clamp(2.2rem,5vw,4rem)}.success-page .public-lede{margin-bottom:28px}.success-mark{display:grid;place-items:center;width:82px;height:82px;border-radius:50%;background:linear-gradient(135deg,var(--orange),var(--orange-2));color:#fff;box-shadow:0 0 0 12px rgba(255,120,0,.1),0 0 45px rgba(255,120,0,.3);margin-bottom:28px;animation:success-pop .55s ease both}@keyframes success-pop{from{opacity:0;transform:scale(.6)}to{opacity:1;transform:scale(1)}}`}</style></main>;
}
