import { ArrowRight, BarChart3, Brain, FileText, MessageCircle, PlayCircle, ShieldCheck, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import './public.css';

const services = [
  [Brain, 'AI dars generatori', 'Mavzularni interaktiv darslarga aylantiring.', ['Misollar va tushuntirishlar', 'Flashcard va testlar', 'Shaxsiylashtirilgan kontent']],
  [PlayCircle, 'Video va hikoya darslar', 'Murakkab mavzularni qiziqarli formatda o‘rganing.', ['AI ovozli hikoyalar', 'Video slaydlar', 'Vizual misollar']],
  [MessageCircle, 'Jonli savol-javob', 'AI yordamchidan istalgan vaqtda javob oling.', ['Tezkor tushuntirish', 'Mavzu bo‘yicha suhbat', '24/7 foydalanish']],
  [Trophy, 'Test va baholash', 'Bilimingizni o‘lchang va rivojlanishni ko‘ring.', ['Avtomatik testlar', 'Aniq baholash', 'Natijalar tarixi']],
  [BarChart3, 'Statistika va progress', 'O‘qish jarayonini raqamlar orqali kuzating.', ['Kunlik statistika', 'Progress grafigi', 'Tavsiyalar']],
  [ShieldCheck, 'Mobil va ishonchli', 'Har qanday qurilmada xavfsiz foydalaning.', ['Responsive interfeys', 'Ishonchli saqlash', 'Tezkor platforma']],
];

export default function ServicesPage() {
  return <main className="public-container"><div className="public-page-heading"><span className="public-eyebrow">Imkoniyatlar</span><h1 className="public-title">Xizmatlarimiz</h1><p className="public-lede">Abdora AI — o‘quv muassasalaringizni AI yordamida osonlashtirish uchun yaratilgan platforma.</p></div><div className="service-grid">{services.map(([Icon, title, text, points]) => <article className="public-card service-card" key={title}><div className="service-icon"><Icon size={21} /></div><h2>{title}</h2><p>{text}</p><ul>{points.map((point) => <li key={point}><span>✓</span>{point}</li>)}</ul></article>)}</div><div className="service-cta public-card"><div><span className="public-eyebrow">Keyingi qadam</span><h2>Imkoniyatlardan bugun foydalaning!</h2></div><Link className="public-button primary" to="/contact">Ariza qoldirish <ArrowRight size={16} /></Link></div><style>{`.public-page-heading{max-width:650px;margin-bottom:52px}.service-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.service-card{padding:25px}.service-icon{display:grid;place-items:center;width:44px;height:44px;border-radius:12px;background:linear-gradient(135deg,var(--orange),var(--orange-2));color:#fff;margin-bottom:22px}.service-card h2{font:600 19px 'Space Grotesk',sans-serif;margin:0 0 9px}.service-card p{color:var(--secondary);font-size:13px;line-height:1.6;margin:0 0 18px}.service-card ul{list-style:none;padding:0;margin:0;display:grid;gap:9px;color:var(--muted);font-size:12px}.service-card li{display:flex;gap:8px}.service-card li span{color:var(--orange)}.service-cta{margin-top:58px;padding:28px 32px;display:flex;align-items:center;justify-content:space-between;gap:20px;background:linear-gradient(110deg,var(--orange),var(--orange-2));color:#211008;border:0}.service-cta .public-eyebrow{color:#552409}.service-cta h2{font:600 25px 'Space Grotesk',sans-serif;margin:9px 0 0}.service-cta .public-button{background:#211008;color:#fff;border:0}@media(max-width:900px){.service-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.service-grid{grid-template-columns:1fr}.service-cta{align-items:flex-start;flex-direction:column;padding:24px}.service-cta h2{font-size:21px}}`}</style></main>;
}
